/** @format */

export const Customers = [
  {
    id: 44,
    itemName: "Ahmed Saloom",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 45,
    itemName: "Mohamed Hamoodi",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 443,
    itemName: "Ali Ismail",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 454,
    itemName: "Ail Hamandi",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },

  {
    id: 44,
    itemName: "Ail Hamandi",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 45,
    itemName: "Ail Hamandi",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 443,
    itemName: "Ail Hamandi",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 454,
    itemName: "Ail Hamandi",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },

  {
    id: 44,
    itemName: "Ahmed Saloom",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 45,
    itemName: "Mohamed Hamoodi",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 443,
    itemName: "Ali Ismail",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 454,
    itemName: "Ail Hamandi",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },
];
export const Products = [
  {
    id: 444,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 64,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Nail System ",
    orderValue: "Athtoplsty",
    price: "119$",
  },
  {
    id: 444,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 64,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Nail System ",
    orderValue: "Athtoplsty",
    price: "119$",
  },
  {
    id: 444,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 64,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Nail System ",
    orderValue: "Athtoplsty",
    price: "119$",
  },
  {
    id: 994,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Dolor",
    mostOrder: "On pipe ",
    orderValue: "Others",
    price: "119$",
  },
  {
    id: 66,
    listName: "product",
    itemName: "S type clavical locking plate",
    itemNumber: "1",
    type: "Dolor",
    mostOrder: "Bone Cement ",
    orderValue: "Others",
    price: "119$",
  },
];
export const Stuff = [
  {
    id: 4445,
    itemName: "Ahmed Saloom",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 484,
    itemName: "Ahmed Saloom",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 664,
    itemName: "Mohamed Hamoodi",
    type: "Dolor",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 44464,
    itemName: "Mohamed Hamoodi",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 4445,
    itemName: "Mohamed Hamoodi",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 484,
    itemName: "Mohamed Hamoodi",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 664,
    itemName: "Ahmed Saloom",
    type: "Dolor",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 44464,
    itemName: "Ahmed Saloom",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
];
