/** @format */

export const Customers = [
  {
    id: 1,
    itemName: "Ahmed ",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 2,
    itemName: "Mohamed",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 3,
    itemName: "Ali",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 4,
    itemName: "Ail ",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },

  {
    id: 5,
    itemName: "Ail ",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 6,
    itemName: "Ail",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 8,
    itemName: "Ail",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 9,
    itemName: "Ail ",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },

  {
    id: 10,
    itemName: "Ahmed ",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 11,
    itemName: "Mohamed ",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 12,
    itemName: "Ali ",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 13,
    itemName: "Ail",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },
];
export const Products = [
  {
    id: 1,
    listName: "product",
    itemName: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 2,
    listName: "product",
    itemName: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Nail System ",
    orderValue: "Athtoplsty",
    price: "119$",
  },
  {
    id: 3,
    listName: "product",
    itemName: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 4,
    listName: "product",
    itemName: "S  locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Nail System ",
    orderValue: "Athtoplsty",
    price: "119$",
  },
  {
    id: 5,
    listName: "product",
    itemName: " locking plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 6,
    listName: "product",
    itemName: "S type plate",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Nail System ",
    orderValue: "Athtoplsty",
    price: "119$",
  },
  {
    id: 7,
    listName: "product",
    itemName: "locking plate",
    itemNumber: "1",
    type: "Dolor",
    mostOrder: "On pipe ",
    orderValue: "Others",
    price: "119$",
  },
  {
    id: 8,
    listName: "product",
    itemName: "S type clavical ",
    itemNumber: "1",
    type: "Dolor",
    mostOrder: "Bone Cement ",
    orderValue: "Others",
    price: "119$",
  },
];
export const Stuff = [
  {
    id: 1,
    itemName: "Ahmed ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 2,
    itemName: "Ahmed ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 3,
    itemName: "Mohamed ",
    type: "Dolor",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 4,
    itemName: "Mohamed",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 5,
    itemName: "Mohamed",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 6,
    itemName: "Mohamed ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 7,
    itemName: "Ahmed ",
    type: "Dolor",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
  {
    id: 8,
    itemName: "Ahmed",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    orderValue: "119",
    ratingRate: "4/5",
  },
];
